[theme]
primaryColor = "#0065BD"
backgroundColor = "#ebe8e8"
secondaryBackgroundColor = "#D9DADB"
textColor = "#050505"
font = "sans-serif"
baseFontSize = 16


[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
